
FROM jupyter/r-notebook:70178b8e48d7 AS build
COPY test-diederik-today3-diederik-environment.yaml .
RUN conda env update -n venv -f test-diederik-today3-diederik-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY test-diederik-today3-diederik.py .

