
FROM qcdis/miniconda3 AS build
COPY print-a-gpelouze-environment.yaml .
RUN conda env update -n venv -f print-a-gpelouze-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY print-a-gpelouze.py .

