
FROM qcdis/miniconda3-multiply AS build
COPY set-user-credentials-joristimmermans-environment.yaml .
RUN conda install -c conda-forge mamba
RUN mamba env update -f set-user-credentials-joristimmermans-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY set-user-credentials-joristimmermans.py .

