
FROM qcdis/miniconda3-pdal AS build
COPY s2-split-big-files-skoulouzis-environment.yaml .
RUN conda env update -n venv -f s2-split-big-files-skoulouzis-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY s2-split-big-files-skoulouzis.py .

