
FROM qcdis/miniconda3-pdal AS build
COPY normalization-01-06-22-shiyifang-environment.yaml .
RUN conda env update -f normalization-01-06-22-shiyifang-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY normalization-01-06-22-shiyifang.py .

