
FROM qcdis/miniconda3 AS build
COPY a-list-dev-user-name-at-domain-com-environment.yaml .
RUN conda install -c conda-forge mamba
RUN mamba env update -f a-list-dev-user-name-at-domain-com-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY a-list-dev-user-name-at-domain-com.py .

