
FROM qcdis/miniconda3-distributed-learning AS build
COPY nn-cifar-cl-skoulouzis-environment.yaml .
RUN conda env update -f nn-cifar-cl-skoulouzis-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY nn-cifar-cl-skoulouzis.py .

