FROM continuumio/miniconda3 AS build
COPY list-knmi-files-den-helder-v02-berendwijers-environment.yaml .
RUN conda install -c conda-forge mamba
RUN mamba env update -f list-knmi-files-den-helder-v02-berendwijers-environment.yaml
RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM qcdis/python-vol2bird AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY list-knmi-files-den-helder-v02-berendwijers.py .

