
FROM qcdis/miniconda3-pdal AS build
COPY retiling-08-04-22-zmzhao-environment.yaml .
RUN conda install -c conda-forge mamba
RUN mamba env update -f retiling-08-04-22-zmzhao-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY retiling-08-04-22-zmzhao.py .

