
FROM qcdis/miniconda3 AS build
COPY process-a-list-spiros-koulouzis-at-lifewatch-eu-environment.yaml .
RUN conda env update -n venv -f process-a-list-spiros-koulouzis-at-lifewatch-eu-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY process-a-list-spiros-koulouzis-at-lifewatch-eu.py .

