name: Build containers on push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  get-changed-files:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    outputs:
      files: ${{ steps.files.outputs.all }}
  build-push:
    needs: [get-changed-files]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Build and push image
        run:  |
          for changed_file in ${{ needs.get-changed-files.outputs.files }}; do
            dir="$(dirname "${changed_file}")"
            if [ "$dir" != ".github/workflows" ]; then
              cd $dir
              dockerfile=`ls Dockerfile.*`
              IFS='.' read -ra names_array <<< "$dockerfile"
              echo Building ${names_array[1]}/${names_array[2]}
              docker build . --file $dockerfile --tag ${names_array[1]}/${names_array[2]}
              echo Pusing ${names_array[1]}/${names_array[2]}
              docker push ${names_array[1]}/${names_array[2]}
            fi
          done