FROM jupyter/r-notebook:70178b8e48d7

USER root 

RUN R -e "install.packages('dplyr', repos='http://cran.rstudio.com')" 
RUN R -e "install.packages('forcats', repos='http://cran.rstudio.com')" 
RUN R -e "install.packages('ggplot2', repos='http://cran.rstudio.com')" 
RUN R -e "install.packages('readr', repos='http://cran.rstudio.com')" 
RUN R -e "install.packages('optparse', repos='http://cran.rstudio.com')" 

RUN mkdir -p /app 
COPY simplecont-diederik.R /app